{
 "title": "CSPM Dashboard (PoC)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "Account",
    "query": "select account_id from aws_policy_results"
   },
   {
    "name": "framework",
    "label": "Policy",
    "query": "select framework from aws_policy_results"
   },
   {
    "name": "category",
    "label": "Category",
    "query": "select category from aws_policy_results;"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "select status from aws_policy_results"
   },
   {
    "name": "nb_alarms",
    "query": "select\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and category in (${category}) and status = 'alarm';"
   },
   {
    "name": "nb_critical_alarms",
    "query": "select\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and category in (${category}) and status = 'alarm' and severity = 'critical';"
   },
   {
    "name": "nb_high_alarms",
    "query": "select\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and category in (${category}) and status = 'alarm' and severity = 'high';"
   },
   {
    "name": "nb_medium_alarms",
    "query": "select\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and category in (${category}) and status = 'alarm' and severity = 'medium';"
   }
  ]
 },
 "panels": [
  {
   "title": "Data Source",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables\n     WHERE  table_schema = 'public'\n     AND    table_name   = 'aws_policy_results'"
    }
   ]
  },
  {
   "title": "Last Fetch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select _cq_sync_time as time, 1 from aws_resources order by _cq_sync_time desc limit 1;"
    }
   ]
  },
  {
   "title": "Last Policy Evaluation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select execution_time as time, 1 from aws_test_results order by execution_time desc limit 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": {
    "content": "<a style=\"background-color:#2196f3;border:none;color:#fff;padding:8px 15px;text-align:center;text-decoration:none;display:inline-block;font-size:13px;border-radius:5px;transition-duration:0.4s;cursor:pointer;\" target=\"_blank\" href=\"http://localhost:7000/generate_pdf_report\" class=\"material-btn\">PDF report</a>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "options": {
    "content": "<a style=\"background-color:#36454F;border:none;color:#fff;padding:8px 15px;text-align:center;text-decoration:none;display:inline-block;font-size:13px;border-radius:5px;transition-duration:0.4s;cursor:pointer;\" target=\"_blank\" href=\"http://localhost:7000/generate_csv_export\" class=\"material-btn\">CSV export</a>"
   }
  },
  { "title": "Policy Evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Maturity",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select\n  framework,\n  category,\n  count(case when status = 'ok' then 1 else null end) as \"Ok\",\n  count(case when status = 'alarm' then 1 else null end) as \"Alarm\"\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and category in (${category}) group by framework, category order by char_length(category) desc;"
    }
   ]
  },
  {
   "title": "Total checks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and category in ($category);"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and category in (${category}) and status = 'alarm';"
    }
   ]
  },
  {
   "title": "Alarms (${nb_alarms})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CRITICAL (${nb_critical_alarms})",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 21, "w": 7, "x": 0, "y": 10 },
     "options": {
      "content": "{{#each data}}\r\n<table width=100%>\r\n  <tr>\r\n    <td style='background-color:#f2495c;'>\r\n      <p style='margin-top:5px; margin-left:10px; margin-right:10px; margin-bottom: 5px;'>\r\n        <b class=\"head\">{{title}}</b>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td>\r\n      <p style='margin-top:10px; margin-left:10px; margin-right:8px; margin-bottom:10px'>\r\n        <b class=\"text\">{{description}}</b>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"border:0px;\">\r\n      <p style='border:0px; text-align: right; margin-right:15px;'>\r\n        <b class=\"arn\">{{resource_name}}</b>\r\n        <a class=\"button\" href=\"{{link}}\" target=\"_blank\">Fix this</a>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n</table>\r\n{{/each}}"
     },
     "targets": [
      {
       "rawSql": "select * \r\nfrom aws_policy_results \r\nwhere \r\n  account_id in (${account_id}) and \r\n  framework in (${framework}) and \r\n  category in (${category}) and \r\n  severity = 'critical' and \r\n  status = 'alarm';"
      }
     ]
    },
    {
     "title": "HIGH (${nb_high_alarms})",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 19, "w": 8, "x": 7, "y": 10 },
     "options": {
      "content": "{{#each data}}\r\n<table width=100%>\r\n  <tr>\r\n    <td style='background-color:#fe8700;'>\r\n      <p style='margin-top:5px; margin-left:10px; margin-right:10px; margin-bottom: 5px;'>\r\n        <b class=\"head\">{{title}}</b>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td>\r\n      <p style='margin-top:10px; margin-left:10px; margin-right:8px; margin-bottom:10px'>\r\n        <b class=\"text\">{{description}}</b>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"border:0px;\">\r\n      <p style='border:0px; text-align: right; margin-right:15px;'>\r\n        <b class=\"arn\">{{resource_name}}</b>\r\n        <a class=\"button\" href=\"{{link}}\" target=\"_blank\">Fix this</a>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n</table>\r\n{{/each}}"
     },
     "targets": [
      {
       "rawSql": "select * \r\nfrom aws_policy_results \r\nwhere \r\n  account_id in (${account_id}) and \r\n  framework in (${framework}) and \r\n  category in (${category}) and \r\n  severity = 'high' and \r\n  status = 'alarm';"
      }
     ]
    },
    {
     "title": "MEDIUM (${nb_medium_alarms})",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 19, "w": 8, "x": 15, "y": 10 },
     "options": {
      "content": "{{#each data}}\r\n<table width=100%>\r\n  <tr>\r\n    <td style='background-color:#5794f2;'>\r\n      <p style='margin-top:5px; margin-left:10px; margin-right:10px; margin-bottom: 5px;'>\r\n        <b class=\"head\">{{title}}</b>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td>\r\n      <p style='margin-top:10px; margin-left:10px; margin-right:8px; margin-bottom:10px'>\r\n        <b class=\"text\">{{description}}</b>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"border:0px;\">\r\n      <p style='border:0px; text-align: right; margin-right:15px;'>\r\n        <b class=\"arn\">{{resource_name}}</b>\r\n        <a class=\"button\" href=\"{{link}}\" target=\"_blank\">Fix this</a>\r\n      </p>\r\n    </td>\r\n  </tr>\r\n</table>\r\n{{/each}}"
     },
     "targets": [
      {
       "rawSql": "select * \r\nfrom aws_policy_results \r\nwhere \r\n  account_id in (${account_id}) and \r\n  framework in (${framework}) and \r\n  category in (${category}) and \r\n  severity = 'medium' and \r\n  status = 'alarm';"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select \r\n  category as \"Category\", \r\n  check_id as \"Check ID\", \r\n  resource_name as \"Resource\", \r\n  title as \"Recommendation\", \r\n  status as \"Status\" \r\nfrom aws_policy_results\r\nwhere account_id in (${account_id}) and framework in (${framework}) and category in (${category}) and status in (${status});"
    }
   ]
  }
 ]
}